[2025-10-07T09:35:17.004+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-07T09:35:17.034+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: minio_to_snowflake.load_snowflake scheduled__2025-10-07T09:22:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2025-10-07T09:35:17.034606+00:00 and task will be retried at 2025-10-07T09:40:08.051761+00:00.
[2025-10-07T09:35:17.037+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
